### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by mrniddala** [BVengo/simple-shulker-preview#1]
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'advanced_runtime_resource_pack'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'advanced_runtime_resource_pack'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	... 2 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'advanced_runtime_resource_pack'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.devtech.arrp.ARRP failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 5 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [modid.mixins.json:ExampleMixin from mod simpleshulkerpreview] from phase [DEFAULT] in config [modid.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'net.fabricmc.example.mixin.ExampleMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:865)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:781)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 20 more
Caused by: java.lang.ClassNotFoundException: The specified mixin 'net.fabricmc.example.mixin.ExampleMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1314)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:858)
	... 23 more

**Comment by BVengo** [comment]
Hi,
Thanks for this update. It looks like you may have other mods installed (advanced_runtime_resource_pack), so could you please give some context about what you were doing when the error occurred?

Useful information includes:
- installed mods and mod versions
- what action you were doing when this error occurred
- where you got the mod jar file from (GitHub, Modrinth, CurseForge)

**Comment by BVengo** [comment]
Sorry, didn't mean to close this issue!

Please see my previous comment.

**Comment by mrniddala** [comment]
Hello!
**The mods I'm using:**
Loading 432 mods:
	- advanced_runtime_resource_pack 0.6.2 via enhancedblockentities
	- advancementplaques 1.4.5
	- adventure-platform-fabric 5.4.0-SNAPSHOT via squaremap
	- amecs 1.3.8+mc.1.19-rc2
	- amecsapi 1.3.6+mc22w17a via amecs
	- animatica 0.5+1.19
	- anvil-crush 1.6.1
	- anvil-display 1.1
	- appleskin 2.4.0+mc1.19
	- architectury 5.10.33
	- armorhide 1.0.1
	- armorsoundtweak 6.0.0
	- auditory 0.0.2-1.19
	- automaticelytra 1.3.1
	- autoswitch 5.1.3-alpha.1
	- autoswitch-api 1.1.0 via autoswitch
	- axolotlviewer 1.0.3
	- backtools 1.19-1
	- badpackets 0.1.2
	- balm-fabric 4.3.0+0
	- bedrockify 1.4.2+mc1.19
	- bedrockskinutility 1.3.0
	- beenfo 1.19-fabric0.53.3-1.3.3
	- bendy-lib 2.0.4 via emotecraft
	- better-christmas-chests 4.0.0+build.14
	- bettermounthud 1.1.4
	- betterpingdisplay 1.1.1
	- bettersafebed 4
	- block-entity-extended-rendering 2.0.0
	- blue_endless_jankson 1.2.1 via jankson
	- boatcam 1.0.3
	- boatiview 0.0.3
	- boatjump 1.1.0-1.19
	- bobby 4.0.0
	- bookshelf 14.1.8
	- borderlessmining 1.1.5+1.19
	- brb 1.6.0
	- breakfree 1.1.0
	- bsvsb 3.0.0
	- c2me 0.2.0+alpha.8.13
	- c2me-base 0.2.0+alpha.8.13 via c2me
	- c2me-client-uncapvd 0.2.0+alpha.8.13 via c2me
	- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.8.13 via c2me
	- c2me-fixes-general-threading-issues 0.2.0+alpha.8.13 via c2me
	- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.8.13 via c2me
	- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.8.13 via c2me
	- c2me-notickvd 0.2.0+alpha.8.13 via c2me
	- c2me-opts-allocs 0.2.0+alpha.8.13 via c2me
	- c2me-opts-chunk-access 0.2.0+alpha.8.13 via c2me
	- c2me-opts-chunkio 0.2.0+alpha.8.13 via c2me
	- c2me-opts-math 0.2.0+alpha.8.13 via c2me
	- c2me-opts-scheduling 0.2.0+alpha.8.13 via c2me
	- c2me-opts-worldgen-general 0.2.0+alpha.8.13 via c2me
	- c2me-opts-worldgen-vanilla 0.2.0+alpha.8.13 via c2me
	- c2me-rewrites-chunkio 0.2.0+alpha.8.13 via c2me
	- c2me-server-utils 0.2.0+alpha.8.13 via c2me
	- c2me-threading-chunkio 0.2.0+alpha.8.13 via c2me
	- c2me-threading-lighting 0.2.0+alpha.8.13 via c2me
	- c2me-threading-scheduling 0.2.0+alpha.8.13 via c2me
	- c2me-threading-worldgen 0.2.0+alpha.8.13 via c2me
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- can-i-mine-this-block 1.3.0
	- capes 1.4.4+1.19
	- cardinal-components-base 5.0.1 via squaremap
	- cardinal-components-entity 5.0.1 via squaremap
	- carpet 1.4.79
	- carpet-autocraftingtable 1.4.57
	- carpet-extra 1.4.79
	- carpet-redcraft-addons 1.4.79
	- carpet-tctc-addition-1_19 2.0.176+d80e88f-beta
	- carpet-tis-addition 1.38.0
	- cateyes 3.2.0
	- cem 0.7.1
	- chat_heads 0.6.0
	- chime 1.3.0
	- citresewn 1.1.1+1.19
	- citresewn-defaults 1.1.1+1.19 via citresewn
	- clear-skies 2.0.94
	- cleardespawn 1.1.8
	- clicksoundfix 1.2
	- clickthrough 1.19-fabric0.53.3-0.4
	- clientsidenoteblocks 2.2
	- cloth-api 4.0.65
	- cloth-basic-math 0.6.1 via cloth-api
	- cloth-client-events-v0 4.0.65 via cloth-api
	- cloth-common-events-v1 4.0.65 via cloth-api
	- cloth-config 7.0.73
	- cloth-scissors-api-v1 4.0.65 via cloth-api
	- cloth-utils-v1 4.0.65 via cloth-api
	- cloud 1.8.0-SNAPSHOT via squaremap
	- cloud_commandframework_cloud-brigadier_ 1.8.0-SNAPSHOT via cloud
	- cloud_commandframework_cloud-core_ 1.8.0-SNAPSHOT via cloud
	- cloud_commandframework_cloud-minecraft-extras 1.8.0-SNAPSHOT via squaremap
	- cloud_commandframework_cloud-services_ 1.8.0-SNAPSHOT via cloud
	- coat 1.0.0-beta.18+mc22w17a via mousewheelie
	- collective-fabric 4.27
	- coloredglowlib 1.3.4
	- colormatic 3.1.2+mc.1.19
	- com_electronwill_night-config_core 3.6.5 via armorsoundtweak
	- com_electronwill_night-config_toml 3.6.5 via armorsoundtweak
	- com_github_imurx_wanakanajava 33cf3b3d37 via localizedbrowser
	- com_github_llamalad7_mixinextras 0.0.11 via cull-less-leaves
	- com_ibm_async_asyncutil 0.1.0 via c2me
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- com_typesafe_config 1.4.2 via bobby
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- completeconfig-base 2.0.0-beta.3 via cem
	- completeconfig-gui-cloth 2.0.0-beta.3 via cem
	- conditional-mixin 0.3.1 via carpet-tis-addition
	- config2brigadier 1.1.3 via fabrictailor
	- connectivity 1.19-3.2
	- continuity 2.0.0+1.19
	- cool_elytra 1.3.1
	- couplings 1.9.0+1.19
	- cr-arrows-info 1.2.1+1.19
	- cr-compass-ribbon 2.8.2+1.19
	- craftingtweaks 15.0.1
	- crawl 0.11.0
	- creativecore 2.7.2
	- creeper_firework 1.3.3
	- crowdin-translate 1.4+1.19 via beenfo
	- crowmap 1.0.1
	- csearcher 0.1.5+mc1.19
	- ctm 1.0.0+1.19
	- cull-less-leaves 1.0.4
	- customstars 1.1+1.19
	- doph 1.0.0
	- draggable-resource-packs 3.0.0+build.6
	- dual_riders 1.1.2
	- durability101 0.0.4
	- durabilitynotifier 1.3.0
	- dynamicfps 2.2.0
	- easyshulkerboxes 4.0.3
	- eatinganimationid 1.9
	- effective 1.2.2
	- effecttooltips 3.0.2
	- emotecraft 2.1.3-SNAPSHOT-build.32
	- enchantment_lore 1.2.7
	- enchantmentcompat 1.0.0
	- enhanced-searchability 3.0.1+build.9
	- enhancedblockentities 0.7.1+1.19
	- entity_texture_features 4.0
	- entitycollisionfpsfix 2.0.0.0
	- entityculling 1.5.2-mc1.19
	- equipmentcompare 1.3.1
	- essential-client 1.19-1.2.3
	- essentialaddons 1.19-1.1.4
	- fabric 0.58.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via armorsoundtweak
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
	- fabric-blockrenderlayer-v1 1.1.18+9ff28f40a9 via fabric
	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.28+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.2.1+07df213ea9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.1.2+a680b9b4a9 via fabric
	- fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.26+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.5+35a03c43a9 via fabric
	- fabric-item-groups-v0 0.3.26+9ff28f40a9 via fabric
	- fabric-key-binding-api-v1 1.0.18+9ff28f40a9 via fabric
	- fabric-keybindings-v0 0.2.16+df3654b3a9 via fabric
	- fabric-language-kotlin 1.8.2+kotlin.1.7.10
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via armorsoundtweak
	- fabric-loot-api-v2 1.1.1+03a4e568a9 via fabric
	- fabric-loot-tables-v1 1.1.4+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.11+33fbc738a9 via fabric
	- fabric-models-v0 0.3.15+9ff28f40a9 via fabric
	- fabric-networking-api-v1 1.1.0+442de8b8a9 via fabric
	- fabric-networking-v0 0.3.15+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.8+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via fabrictailor
	- fabric-registry-sync-v0 0.9.18+23c4cfefa9 via fabric
	- fabric-renderer-api-v1 1.0.8+9ff28f40a9 via fabric
	- fabric-renderer-indigo 0.6.10+5187d39fa9 via fabric
	- fabric-renderer-registries-v1 3.2.18+df3654b3a9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-rendering-v0 1.1.20+df3654b3a9 via fabric
	- fabric-rendering-v1 1.10.14+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.6+5f1a85e0a9 via fabric
	- fabric-screen-api-v1 1.0.24+f05effafa9 via fabric
	- fabric-screen-handler-api-v1 1.2.7+9ff28f40a9 via fabric
	- fabric-textures-v0 1.0.18+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.8
	- fabricskyboxes 0.5.7
	- fabrictailor 1.8.4
	- fallingleaves 1.12.1+1.19
	- fastload 1.1.5
	- fastopenlinksandfolders 1.1.1
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via collective-fabric
	- flytre_lib 1.8.8
	- forcecloseloadingscreen 1.1.1
	- forgeconfigapiport 4.0.0
	- forgetmechunk 1.0.4-1.18.X-1.19.X
	- foxglow 1.3.0
	- froggy_flies 1.0.0
	- fuelinfo 1.0+1.19
	- fullscreeno 1.0.0
	- gbfabrictools 1.3.4+1.19 via beenfo
	- ghastly_wail 1.0.7
	- giantspawn-fabric 2.9
	- hatlist 1.3
	- helpfulhitboxes 2.1.0
	- highlighter 1.1.2
	- hopperspeedsim 1.1
	- horsebuff 2.0.1
	- horsedebug 1.2.4
	- horseinboat 1.1.3
	- horseinfo 0.4.2-1.19
	- iceberg 1.0.38
	- identity 2.5.0-1.19
	- illuminations 1.10.8
	- impactfulweather 4.0.1
	- indium 1.0.6+mc1.19
	- interrecipebrowser 1.0.0
	- inventory_control_tweaks 1.3.16
	- inventoryessentials 5.0.0
	- inventorymanagement 1.0.3
	- inventoryprofilesnext 1.6.1
	- inventorytabs 0.9.beta-1.19.x
	- invmove 0.8.0
	- io_leangen_geantyref_geantyref 1.3.13 via bobby
	- iris 1.2.5
	- itemborders 1.1.6
	- itemcounts 1.0.3+mc1.19
	- ivan-carpet-addition 2.1.1
	- jankson 4.1.1+j1.2.1 via libgui
	- java 17
	- jukeboxparticles 1.0.0
	- jumpoverfences 1.16-0.0.3
	- jumpyboat 3.0-1.19
	- kanos_config 0.3.1+1.14.4-1.19 via statement
	- keep-my-hand 1.0.0
	- keymap 0.6.0-beta.0+1.19
	- kirin 1.11.0 via presencefootsteps
	- krypton 0.2.0
	- kyrptconfig 1.4.14-1.19 via quickshulker
	- lambdabettergrass 1.3.0+1.19
	- lambdynlights 2.1.2+1.19
	- languagereload 1.3.1
	- layercontrol 1.0.2+mc1.19
	- lazydfu 0.1.3
	- legendarytooltips 1.2.6
	- letsleepingdogslie 1.1.0
	- libgui 6.0.0-beta.5+1.19-pre1 via stendhal
	- libninepatch 1.1.0 via libgui
	- lithium 0.8.1
	- llamasteeds 2022.6.8
	- localizedbrowser 2.0.0
	- logical_zoom 0.0.15
	- loud_leads 1.0.1+mc1.19
	- magiclib-1_19 0.5.32
	- make_bubbles_pop 0.0.2-1.19
	- malilib 0.12.1
	- mambience 5.2.0+1.19
	- map-in-slot 1.0.2
	- map_saver 1.0.1-1.19
	- maptooltip 2.0.0
	- memoryleakfix 1.19-0.5.4
	- merchantmarkers 1.2.2
	- microdurability 0.3.6+1.19
	- microdurability-core 0.3.6 via microdurability
	- midnightlib 0.5.2
	- minecarttweaks 1.6
	- minecraft 1.19
	- minitweaks 1.19-1.3.1
	- mipmaplevelandlanguagefix 1.0.0
	- mm 2.3 via crawl
	- moderate-loading-screen 1.1.3+1.19
	- modmenu 4.0.0
	- modsettings 1.1.0+1.19
	- monsters_in_the_closet 1.0.4+1.19
	- morechathistory 1.1.0
	- moreculling 1.19-0.6.1
	- mousetweaks 2.22
	- mousewheelie 1.10.2+mc1.19-pre1
	- multiconnect-api 1.5.10 via essential-client
	- mystuff 1.1.0
	- namepain 1.4.0
	- net_kyori_adventure-api 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-key 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-platform-api 4.1.1 via adventure-platform-fabric
	- net_kyori_adventure-text-logger-slf4j 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-minimessage 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-gson 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-plain 4.11.0 via adventure-platform-fabric
	- net_kyori_examination-api 1.3.0 via adventure-platform-fabric
	- net_kyori_examination-string 1.3.0 via adventure-platform-fabric
	- nicerportals 1.0.0
	- nis 1.0.0
	- no_angled_brackets 1.0.1
	- norefreshscroll 1.0.0
	- notenoughanimations 1.6.0
	- notenoughcrashes 4.1.6+1.19
	- now-playing 1.4.1
	- offershud 1.19-1.1.0
	- omega-config 1.2.3-1.18.1 via capes
	- openmcfoldermod 1.0.0
	- opitems 1.2.2
	- optigui 1.1.1
	- org_aeonbits_owner_owner 1.0.12 via autoswitch
	- org_anarres_jcpp 1.4.14 via iris
	- org_apache_commons_commons-text 1.9 via optigui
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- org_joml_joml 1.10.4 via sodium
	- org_spongepowered_configurate-core 4.1.2 via bobby
	- org_spongepowered_configurate-hocon 4.1.2 via bobby
	- org_threadly_threadly 7.0 via c2me
	- org_yaml_snakeyaml 1.30 via carpet-tis-addition
	- oscimate_soulflame 1.0.0
	- paperdoll 1.1.0-mc1.19
	- particlerain 2.0.0
	- pca 0.2.5-alpha+1703874
	- pickupnotifications 1.2.4
	- pistorder 1.5.0
	- playlist 1.0.1
	- pling 1.5.0
	- portal_accessibility 1.0.0-mc1.19
	- portalsgui 1.0.0
	- presencefootsteps 1.6.1
	- pride 1.1.2+1.19 via lambdynlights
	- publicguiannouncement 4.0.0.0
	- puzzle 1.3.4-1.19
	- puzzle-base 1.3.4-1.19 via puzzle
	- puzzle-gui 1.3.4-1.19 via puzzle
	- puzzle-models 1.3.4-1.19 via puzzle
	- puzzle-splashscreen 1.3.4-1.19 via puzzle
	- puzzleslib 4.0.17
	- quickshulker 1.3.8-1.19
	- rad 1.0.2
	- raised 1.1.2
	- raknetify 0.1.0+alpha.5.0
	- realisticitemdrops 1.1-1.19
	- recipecache 0.2.0-1.19
	- reeses-sodium-options 1.4.4+mc1.19-build.47
	- reputation 0.1.3+1.19
	- roughlyenoughitems 9.1.517
	- roughlyenoughprofessions 1.1.0
	- roughlyenoughresources 2.6.0
	- roughlysearchable 2.5.0+1.19
	- roundalib 0.1.8 via enchantmentcompat
	- rsls 1.0.0
	- rsmm_fabric 1.8.0
	- rug 1.19-1.3.4
	- screaminggoats 1.0
	- searchablecontainers 2.0.2+mc1.19
	- servertick 1.7
	- sgui 1.1.1+1.19 via rug
	- sharpness-particles 1.0.0
	- sheepconsistency 1.0.4
	- showmeyourskin 1.2.1+1.19
	- shulkerboxtooltip 3.0.10+1.19
	- shulkerutils 1.0.4-1.19 via quickshulker
	- slimechunkf3 1.4
	- slimyfloor 1.19-1.2.4
	- smoothboot 1.19-1.7.1
	- smoothscrollingeverywhere 3.0.3-unstable
	- smoothswapping 0.4.5
	- sodium 0.4.2+build.16
	- sodium-extra 0.4.6+mc1.19-build.47
	- sound_physics_remastered 1.19-1.0.11
	- sparkle 1.0.3
	- speedtrading 2.1.0+1.19
	- spidersproducewebs-fabric 1.7
	- spruceui 4.0.0+1.19 via block-entity-extended-rendering
	- spyzoom 2.0.0
	- squaremap 1.1.7-SNAPSHOT+a2b458a
	- stairautojump 0.0.3
	- starlight 1.1.1+fabric.ae22326
	- statement 4.2.4+1.14.4-1.19.1
	- statement_vanilla_compatibility 1.0.1+1.16.5-1.17 via statement
	- stendhal 1.3.3-1.19
	- stylisheffects 4.1.2
	- talkbubbles 1.0.2
	- telepistons 1.1.2_dev
	- thorium 1.3.1
	- timestamp_chat 2.2.1
	- tipsmod 6.0.4
	- tooltipfix 1.0.5-1.19
	- toomanybinds 0.3.2+1.19
	- toomanybinds-compat-1-16 0.3.2+1.16 via toomanybinds-compat-1-17
	- toomanybinds-compat-1-17 0.3.2+1.17 via toomanybinds-compat-1-18-2
	- toomanybinds-compat-1-18-2 0.3.2+1.18.2 via toomanybinds-compat-1-19
	- toomanybinds-compat-1-19 0.3.2+1.19 via toomanybinds
	- toomanybinds-core 0.3.2 via toomanybinds-compat-1-16
	- totos-carpet-tweaks 0.2.5
	- tweed4_annotated 1.3.1+mc22w17a via mousewheelie
	- tweed4_base 1.6.0+mc22w17a via mousewheelie
	- tweed4_data 1.2.1+mc22w17a via mousewheelie
	- tweed4_data_hjson 1.1.1+mc22w17a via mousewheelie
	- tweed4_tailor_coat 1.1.3+mc22w17a via mousewheelie
	- tweed4_tailor_screen 1.1.1+mc22w17a via mousewheelie
	- unbad_redstone 1.0.1
	- vectorientation 1.0.1a
	- visuality 0.5.0
	- vmp 0.2.0+beta.6.28
	- walljump 1.4.7+1.19
	- waveycapes 1.2.0
	- whats_that_slot 1.3.0+1.19
	- wildfire_gender 1.19-3.0.0
	- wpit 1.5.1+1.19
	- wthit 5.8.0
	- wthit-plugins 1.0.6+1.19
	- xaerominimap 22.12.0
	- xaeroworldmap 1.26.1
	- youritemsaresafe-fabric 1.2
	- zombiehorsespawn-fabric 3.1

I was removing the mod from the mods folder. I was downloading the mod from Curse.
Maybe it is related to other mods which making things with the shulker boxes?
**They would be:**
- ShulkerBoxTooltips
- EasyShulkerBoxes

**Comment by BVengo** [comment]
Quite the list! Thanks for this, I'll look into it as soon as I'm available.

**Comment by Fuzss** [comment]
You need to give `modid.mixins.json` a unique name (`simpleshulkerpreview.mixins.json` preferably). If another mod provides this file with the same name as is the case here they'll clash. `modid.mixins.json` is the name used in the Fabric example mod, so it's likely another mod forgot to change it as well.

**Comment by BVengo** [comment]
Thanks @Fuzss, I thought I'd adjusted that but must have missed it!
@mrniddala I've pushed a new release that you can download in my GitHub releases, and I'll be uploading to CurseForge shortly too.

**Comment by mrniddala** [comment]
It works without any problems and looks super fancy, yay!

**Comment by BVengo** [comment]
Fantastic - enjoy!
