### ISSUE TITLE
Compass3D (Derivative Work)

### ISSUE THREAD

**Issue by AdamRaichu** [BVengo/simple-shulker-preview#15]
I have forked this repo and made a mod I'm calling [Compass3D](https://modrinth.com/mod/compass3d) with completely different intent (y-axis indication of compass direction) but using roughly the same code. As a thank you to @BVengo for doing developing most of the code I ended up using and choosing a license that allows for modification, I invited him to the project on Modrinth and plan to weight 5% of the monetization of the project to him.

**Comment by BVengo** [comment]
It's absolutely awesome to hear you found it useful for more than just my implementation! Not to mention that it's a great idea, and I'll be using your mod myself going forward. I seriously appreciate the additional invite on Modrinth, and will join you over there :)
