### ISSUE TITLE
1.20 Update

### ISSUE THREAD

**Issue by AdamRaichu** [BVengo/simple-shulker-preview#17]
The 1.20 update made breaking changes to the way items are rendered in the GUI. I've been looking through the code (yarn `1.20+build.1`) and I found the following things.

- Many methods were removed from `ItemRenderer` (including `renderGuiItemIcon`).
- The [Fabric guide](https://fabricmc.net/2023/05/25/120.html) says that in many places `DrawContext` is now used instead of `MatrixStack`.
- `net.minecraft.client.gui.hud.InGameHud.renderHotbarItem` uses `DrawContext.drawItemInSlot(TextRenderer, ItemStack, int, int)` in 1.20 instead of what was used in 1.19.4 (`ItemRenderer.renderGuiItemOverlay(MatrixStack, TextRenderer, ItemStack, int, int)`)`
  - Those two integers are called `x` and `y` in the 1.20 code, but the 1.19.4 appears to use the original parameter names (`i` and `j`).

If I figure out how to make the mixin work in 1.20 I will make a PR.

**Comment by BVengo** [comment]
Thanks Adam, appreciate it.

I probably won't have a chance to review until after the 19th of June, so a PR would be amazing if you get the chance.

**Comment by AdamRaichu** [comment]
Resolved by #18.
