### ISSUE TITLE
Update Modrinth mod summary

### ISSUE THREAD

**Issue by slavalamp** [BVengo/simple-shulker-preview#24]
### Request Description

The summary currently says the mod displays "the icon of the first item" which makes it sound as if that's the only thing it can do and caused me to ignore the mod for a weeks while it had exactly the function I needed (only displaying an icon if there's only one item type)... I suggest changing it to "an icon indicating the contents of a shulker" like in the description.

**Comment by BVengo** [comment]
Ah yes, thanks for this. I've completely forgotten the GitHub description since I first built the project.
All fixed!
