### ISSUE TITLE
[Feature]: Have Display Item show on the block when you place it down (using a local cache)

### ISSUE THREAD

**Issue by Boden-C** [BVengo/simple-shulker-preview#29]
### Request Description

While the server doesn't send placed shulker contents to the client, it might be possible if you cache the BlockPos and display icon locally every time you place a shulker box.

The example image is from [Shulker+](https://modrinth.com/mod/shulker+) though that is done by both client and server

This would probably be a lot harder than my other issue #28 though

### Images

![image](https://github.com/BVengo/simple-shulker-preview/assets/70297682/180a32a1-bd3a-498a-840b-bdbcf19b85ef)

**Comment by AdamRaichu** [comment]
Linking #27 for context.

**Comment by BVengo** [comment]
Thanks Boden.

It's an awesome mod idea that I'd like to implement, but for now I'll mark it as out of scope. I know there's been a couple of requests for it (which I won't forget!), but unfortunately I don't see myself finding the time to implement it as thoroughly as I would like to in the near future.
