### ISSUE TITLE
[Feature]: Display Item: most

### ISSUE THREAD

**Issue by supersaiyansubtlety** [BVengo/simple-shulker-preview#3]
### Request Description

Could you add an option to display the item with there's most of in the shulker?

**Comment by BVengo** [comment]
Sure thing! I imagine it would be added to the "Display Item" config - currently it's First or Last, but I can add Most too. If you have a better naming suggestion then I'd like to hear it :)

It probably won't be implemented as rapidly as my previous releases though, as mentioned on your other feature request.

**Comment by supersaiyansubtlety** [comment]
"Most" under "Display Item" sounds good, that's what I was imagining.

**Comment by BVengo** [comment]
All added, and 'Least' was included for completion :)
