### ISSUE TITLE
Update to 1.21?

### ISSUE THREAD

**Issue by akasnowmaaan** [BVengo/simple-shulker-preview#34]
This mod is so great for quality of life in the game. 
I hope you can keep it going!

**Comment by BVengo** [comment]
Glad you enjoy it! There will be an update, I've just been busy on my honeymoon.

In the meantime, a member on my [discord](https://discord.com/invite/gyTa5v7kKk) put together a 1.21 update based on my dev code. You can see it in the simpleshulkerpreview channel.
