### ISSUE TITLE
Huge W.

### ISSUE THREAD

**Issue by geeatsu** [BVengo/simple-shulker-preview#36]
Not a bug at all, just wanted to say congrats for your honeymoon/marriage. Saw it on Modrinth's update. Couldn't find anywhere else to send a message. Hope it was fun! Have a great week.

**Comment by BVengo** [comment]
Hahaha thanks so much. Appreciate the message! Have a great week too :)

I do have [Discord](https://discord.com/invite/gyTa5v7kKk) if you ever want to chat!
