### ISSUE TITLE
Stacked shulker support

### ISSUE THREAD

**Issue by mrniddala** [BVengo/simple-shulker-preview#5]
### Request Description

Hello, if you stack shulker boxes with the same items (like 27x stone) the icon won't show.
It would be nicee if you could add support for this case.
Greetings.

**Comment by BVengo** [comment]
Hi there!

I'm not sure what you mean by this - I can't replicate an unexpected scenario where the icon isn't showing. You mentioned 'stacking shulker boxes' - are you talking about functionality added by another mod?

**Comment by mrniddala** [comment]
I mean this here:

![image](https://user-images.githubusercontent.com/75373609/184285225-0cfeca21-391f-4c87-982d-d734439bb298.png)

I have three shulker boxes stacked with the same items. But it doesn't show me the item icon :(
It is a feature from a carpet extension. Maybe the mod "AllStackable" has the same behaviour.

**Comment by BVengo** [comment]
Perfect! Thanks. I'll leave this issue open for now until I have more time to look into it in the future, but it definitely seems like a useful feature to have.

**Comment by mrniddala** [comment]
Thanks 😊

**Comment by BVengo** [comment]
Merged changes now implement this for version 2.0! Keep an eye out, but it may not be released this week because I'm quite busy and also have one more feature I'm still working on. (Copying this message across all 3 issues).

Will close this issue now.
