### ISSUE TITLE
Custom Mob Head support

### ISSUE THREAD

**Issue by mrniddala** [BVengo/simple-shulker-preview#6]
### Request Description

Hello, I was testing these here:
https://www.curseforge.com/minecraft/mc-mods/just-mob-heads-fabric
https://www.curseforge.com/minecraft/customization/all-mob-heads

I think these two aren't either supported:
https://modrinth.com/mod/headindex
https://modrinth.com/mod/microcutting

Would be nicee to have support for this.
Normal heads working as usual. (Creeper, Skeleton, Zombie)
I think player heads are not working too.

Greetings.

### Images

![image](https://user-images.githubusercontent.com/75373609/184814216-bfecc281-7eda-4abb-802e-8ba8c97978b8.png)

### Fabric Version

Latest

**Comment by BVengo** [comment]
Thanks for this. It makes sense, because I'm just directly rendering the item without taking into account their nbt data.

I appreciate all this testing you've been doing! Life has gotten busy so I haven't had much chance to do it myself.

**Comment by mrniddala** [comment]
It is one of my favourite mods ❤️
I think I found now all small things, when I find something else I let you know.

**Comment by mrniddala** [comment]
Hello @BVengo, one more thing came into my mind.
Maybe add support for enchanted items too - that the enchantment glint would be visible.

**Comment by BVengo** [comment]
Merged changes now implement this for version 2.0! Keep an eye out, but it may not be released this week because I'm quite busy and also have one more feature I'm still working on. (Copying this message across all 3 issues).

Will close this issue now.
