### ISSUE TITLE
Identify enchanted items

### ISSUE THREAD

**Issue by BVengo** [BVengo/simple-shulker-preview#7]
Hello @BVengo, one more thing came into my mind.
Maybe add support for enchanted items too - that the enchantment glint would be visible.

_Originally posted by @mrniddala in https://github.com/BVengo/simple-shulker-preview/issues/6#issuecomment-1221646236_

**Comment by BVengo** [comment]
Hey @mrnidalla. Thanks for the suggestion!

The reason I didn't add this was because there is no way to distinguish between one set of enchanted items over another based on just the icon, and I figured it would be more useful to have all of one item grouped (e.g. diamond chestplate or enchanted diamond chestplate treated the same). 

I may add a config for grouping enchanted items since you believe it will be useful. If this feature is enabled and you select the "unique" display option, then it will only show the item if all diamond chestplates are enchanted, or all diamond chestplates inside are unenchanted (based on the earlier example). However, it won't distinguish between the enchantments themselves - i.e. all enchanted diamond chestplates will be treated as one, no matter their enchantment.

This won't impact enchanted books because they are already a separate item from a normal book, so I believe it will already show that glint.

Hope that makes sense?

**Comment by mrniddala** [comment]
Yep, just show the first or last item enchantment if enchanted, very helpful.
I will try the mod directly when it is released 😊

**Comment by BVengo** [comment]
Merged changes now implement this for version 2.0! Keep an eye out, but it may not be released this week because I'm quite busy and also have one more feature I'm still working on. (Copying this message across all 3 issues).

Will close this issue now.
