### ISSUE TITLE
[Bug]: Mod causes PolyMc and ATLauncher to stall indefinitely on windows 

### ISSUE THREAD

**Issue by theendercore** [BVengo/simple-shulker-preview#9]
### Describe the Bug

When downloading modpack (and mods have not test this though) on the PolyMC and AT Launchers it fully stops and does not continue do to illegal charter in the name. I found out about this when my friends tried to install the modpack i made. I use linux they use windows. 

### Steps to Reproduce

Install a modpack contain the mod on Poly and AT.
Once it seams like all the mods will be downloaded it will stall on the mod (which can be seen in logs).

For reference the modpack i use (only v1.2.1 includes the mod) :
https://modrinth.com/modpack/end-client/version/1.2.1

### Expected Behavior

No to stall Poly or AT.
And not to make windows cry.

### Mod Version

1.19.* v2.0

### Additional Context

please fix this. its such a small issue but this mod is very cool and i would love if i could include it in my modpack.

**Comment by theendercore** [comment]
How to fix:
Replace * with x in name

**Comment by BVengo** [comment]
Ouch, thanks windows! I use Linux too, so completely forgot that may be an issue.

I'll upload another version shortly.

**Comment by BVengo** [comment]
Thanks for letting me know about that, it's an embarrassingly simple mistake!

I've updated releases on CurseForge, Modrinth, and GitHub to v2.1. See https://github.com/BVengo/simple-shulker-preview/releases/tag/v2.1 for changelogs. Let me know if you run into any further problems :)

**Comment by theendercore** [comment]
Thanks for fixing this so fast :)
And is okay. I also would have forgotten then the Windows has in inferior file system. :)
